### ISSUE TITLE
Can not subscribe `Existing subscription to channel`

### ISSUE THREAD

**Issue by raihan** [pusher/pusher-websocket-swift#106]
Hello,

Pusher subscription is not working on device(iPhone 6s & iPad air 2), I am trying on  Xcode 8.1 &  iOS 10.1. After subscribing it is not calling delegate method `subscribedToChannel` and neither
`failedToSubscribeToChanne` and getting following log on debugLog:` [PUSHER DEBUG] websocketDidReceiveMessage {"event":"pusher:error","data":{"code":null,"message":"Existing subscription to channel ls.message.44080_ls.private.18659"}}`

I have also upgraded from 3.0.0 to 4.0.0.
My pusher integration code is as following:

```
let pusher = Pusher(key: kPusherKey, options: PusherClientOptions(
        autoReconnect: true
    ))

```

after that connecting & setting delegate

```
        if pusher.connection.connectionState == .disconnected
        {
            pusher.connect()
            pusher.connection.delegate = self
        }

```

and then subscribing channel & binding event.

```
        channel = pusher.subscribe(getChannelName())
        eventName = channel.bind(eventName:kPusherNotifEventMessage, callback: { data -> Void in
                print("notif_comment message received: \(data)")
                                
            })
```

also disconnecting as followings on `viewDidDisappear` 

```
        pusher.unsubscribe(getChannelName())
        channel.unbindAll()
        pusher.unbind(callbackId: eventName)
        pusher.disconnect()
```
Please let me know how can I fix this or is it a issue on pusher sdk.

Thanks,
Zubair Raihan

**Comment by hamchapman** [comment]
The error message that's getting logged suggests that you're already subscribed. Could this be the case? If you're getting that logged out then it's likely not that the client is getting inconsistent state internally, but just that the client has called subscribe once, subscribed successfully, then for whatever reason it attempts to subscribe to the same channel again.

If that is wrong or the error persists, please could you attach a sample project that exhibits the problem so I can debug?

Thanks!

**Comment by raihan** [comment]
hello @hamchapman , just prepared a sample project. Please see this. This scenario don't occur on simulator, but occurs on device. Please let me know your findings on device. Thanks.
[PusherSample.zip](https://github.com/pusher/pusher-websocket-swift/files/585845/PusherSample.zip)

**Comment by hamchapman** [comment]
Thanks a lot @raihan!

I've worked out what's going on. The error occurs because of the ordering of some code in the part of the library that handles receiving a message that states that the connection has been established: https://github.com/pusher/pusher-websocket-swift/blob/master/Source/PusherConnection.swift#L306-L324

Specifically, you can see on line 310 where the `updateConnectionState` function is called, this leads to the `changedConnectionState` delegate function being called. This is where your code that subscribes to the channel is setup to run. So your `subscribe` call is made and seeing as the connection is already marked as connected, an attempt is made immediately to subscribe. However, you can also see at the bottom of the `handleConnectionEstablishedEvent` function that for any channels that aren't subscribed yet, attempts are made to subscribe to them. 

Because of the asynchronous nature of subscriptions being made, the first subscription attempt hasn't finished by the time this part of the code is run, so a second attempt is made, leading to the error you're seeing.

What I'd recommend is that you don't make calls to `subscribe` inside the `changedConnectionState` function, otherwise you can get these kinds of race conditions. I will also look into changing the ordering of some of the code int the `handleConnectionEstablishedEvent ` function to help ensure that this sort of error can't occur as it has for you.

In your case I'd move the subscribe call to the `setupPusher` function, as you can see that you don't need to be connected in order to call `subscribe`.

**Comment by raihan** [comment]
Hello @hamchapman thanks for quick feedback. initially subscribe call was on `setupPusher` method that time was facing same results, that's why I moved that to inside `changedConnectionState` to ensure I am subscribing after getting connected. I have tried again with `subscribe` on `setupPusher` method but also having same results. Please see the attached project.

But one thing is bugging me, it works fine on simulator but not on device, do we need add any specific configurations ?

[PusherSample.zip](https://github.com/pusher/pusher-websocket-swift/files/585972/PusherSample.zip)

**Comment by hamchapman** [comment]
Thanks again for the project. I think this is actually the same problem as in #51. The underlying socket is not marked as connected by the time the subscribe event is (attempted to be) sent over the socket.

**Comment by hamchapman** [comment]
#108 should fix this for you (it did in my local testing).

I'll be releasing a version 4.0.2 today :

**Comment by raihan** [comment]
thanks @hamchapman , will check & confirm you.

**Comment by raihan** [comment]
wrks great! @hamchapman.
