### ISSUE TITLE
Custom request handling with alamofire and pusher authenticated channels

### ISSUE THREAD

**Issue by pedromcunha** [pusher/pusher-websocket-swift#127]
We are currently using Alamofire for handling [authentication and refresh flow](https://github.com/Alamofire/Alamofire#requestretrier). 

When implementing the pusher SDK I noticed that an authorization header is required. Is there any way to set it up that pusher uses a custom request manager so we can maintain one flow instead of duplicating two oauth flows?

**Comment by hamchapman** [comment]
The library internals will make a request to your authentication endpoint (as specified in the `PusherClientOptions` you provide on client instantiation) for each subscription that the client attempts to make to an authenticated channel, i.e. private or presence channels. 

The library could be updated to provide a manual auth hook so that you could call subscribe with a pre-generated auth value, in which case you could have your app make a single request to your auth endpoint to fetch a session token (or equivalent) as well as the necessary Pusher channel subscription auth value(s). Currently the library doesn't offer this but it shouldn't be too easy to add as an option.

The short summary of the required changes would be that `subscribe` (and `subscribeToPresenceChannel`) would need to be updated to accept an optional `auth` `String` value: https://github.com/pusher/pusher-websocket-swift/blob/master/Source/PusherSwift.swift#L81-L86

Then the `PusherConnection` `subscribe` and `subscribeToPresenceChannel` functions would similarly need to be updated to accept an `auth` `String`: https://github.com/pusher/pusher-websocket-swift/blob/master/Source/PusherConnection.swift#L102-L113

Finally the `authorize` function in `PusherConnection` would need to be updated to accept the `auth` `String` and then if one is provided it should just attempt the subscription using that string.

On your server you'd then need to know the channel(s) that a given user who is logging in would want to be subscribing to on initial load and then generate the appropriate `auth` values for each of those subscriptions. 

It is important to note, however, that all of this is dependent on the fact that an initial connection to the Pusher web socket servers has been made such that the client has a valid `socketId` value to pass to your server when then generating the subscription `auth` values.

**Comment by pedromcunha** [comment]
I think a manual auth hook would solve a lot of our issues. What's the timeline with getting this into the SDK and when can we see a point release with the changes?

**Comment by hamchapman** [comment]
I'll take a look at making changes to the SDK today

**Comment by hamchapman** [comment]
I've created a pull request (#129) which should give you what you need and shows an example of what you need to do. Let me know there if anything is unclear or if it's not working for you.

**Comment by pedromcunha** [comment]
Looks good to me. Thanks for supporting this flow. When will it be merged in?

**Comment by hamchapman** [comment]
Waiting for confirmation that PR #129 is suitable - closing for now though.
