### ISSUE TITLE
Carthage Integration of pusher and uploading app to iTunes errors

### ISSUE THREAD

**Issue by chauvincent** [pusher/pusher-websocket-swift#166]
### What is the issue?

I integrated pusher swift with Carthage and added the .framework to my project and attempted to upload to iTunes. I received the error below. I also tried to integrate it several times including adding a run script following the Carthage docs into the build phases but no luck. in addition, I tried to enable bit code and It still produced more errors. 

Error from iTunes:
Invalid Binary Architecture - iOS 3.0 introduced support for multiple binary architectures. If your binary is built for multiple architectures, your Info.plist must have a MinimumOSVersion key with a value of at least 3.0. Additionally, if your app is intended to support earlier iPhone and iPod touch models, your app must contain at least an armv6 binary; "thin" armv7-only binaries will not be accepted unless the armv7 required device capability is also present in the Info.plist UIRequiredDeviceCapabilities key or the MinimumOSVersion key has a value of 4.3 or higher.

Specifically, we found the following unsupported architectures in your binary:

x86_64
i386
For more information, see Technical Q&A QA1707 at: http://developer.apple.com/iphone/library/qa/qa2010/qa1707.html.

Invalid Mach-O Format - The Mach-O in bundle "MN Staging 4.app/Frameworks/PusherSwift.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains armv7(bitcode) and arm64(bitcode), while the nested bundle Mach-O contains X86_64ALL(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting.

Invalid Segment Alignment - The app binary at 'MN Staging 4.app/Frameworks/PusherSwift.framework/PusherSwift' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.

Invalid Encryption Info - The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker.

Though you are not required to fix the following issues, we wanted to make you aware of them

... 

### Is it a crash report? Submit stack traces or anything that you think would help

...

### Any improvements you suggest

Enable bitcode? in the project
...

---- 

CC @pusher/mobile

**Comment by hamchapman** [comment]
@chauvincent It's likely because the latest version of the library was built with an older version of Xcode and if you're using Carthage without the `--no-use-binaries` flag then you'll be downloading the binary version rather than building it locally.

Try running `carthage update --no-use-binaries` and see if that fixes it for you.

**Comment by addbrick** [comment]
@hamchapman I work with @chauvincent and started to look into the issue. Thanks for the quick response.

I made sure Carthage is building the framework instead of using a binary, but we are still getting the same errors. But it looks like this might be an issue with Carthage. We have opened an issue with them, linking it here to keep track https://github.com/Carthage/Carthage/issues/2292.

**Comment by hamchapman** [comment]
Thanks for the update - let me know if there's anything I can help out with to get to the bottom of the issue!

**Comment by hamchapman** [comment]
Closing as stale. Feel free to reopen if things point to the error being related specifically to PusherSwift. Thanks!
