### ISSUE TITLE
Make TaskQueue and Reachability dependencies "internal"

### ISSUE THREAD

**Issue by hamchapman** [pusher/pusher-websocket-swift#179]
### What is the issue?

https://github.com/pusher/pusher-websocket-swift/commit/2ce625e4ebe95c147f4450f80b7cd7622bff3bb0#commitcomment-28416931

---- 

CC @pusher/mobile

**Comment by lordcodes** [comment]
I would definitely prefer to avoid having extra frameworks being linked in the app as well. However, I'm not sure if internal dependencies are a good idea.

For example, if an app uses TaskQueue / Reachability, then those dependencies would be included twice (once by the app through Carthage) and once internally within pusher.

Are these things something that can just be implemented within Pusher without needing the dependencies?

**Comment by nebiros** [comment]
Also, we use `ReachabilitySwift`, current version: `4.3.0`. Now, we have a conflict between `PusherSwift` and our `Podfile`, we can't update `PusherSwift` to `6.1.0` because we use `ReachabilitySwift 4.3.0`, the only way to update `PusherSwift` is to downgrade `ReachabilitySwift` to `4.1.0` which is the pinned version in your spec, :\

**Comment by imann24** [comment]
Also running into a dependency conflict with `ReachabilitySwift`. Would be great to see this change or an equivalent solution.

**Comment by danielrbrowne** [comment]
Reachability is now no longer a dependency of this SDK, as of the v9.1.0 release, and TaskQueue was also removed some time ago. Therefore this issue is now irrelevant.
