### ISSUE TITLE
OperationQueue blocking main thread, make application freeze

### ISSUE THREAD

**Issue by rudysuharyadi** [pusher/pusher-websocket-swift#206]
### Steps to reproduce

When application receive hundred of pusher call from backend services, sometimes application will freeze. When we debug it, it shows that some operationQueue inside pusher library is blocking main thread with waitUntilAllOperationAreFinished. This wait never end and stuck forever.

### Expected behavior

Operation should not stuck

### Actual behavior

There is some operation that stuck and never finished.

### Any improvements you suggest

I dont have any suggestion for now.

<img width="1680" alt="screen shot 2019-01-14 at 17 09 41" src="https://user-images.githubusercontent.com/1543486/51293797-f578a900-1a42-11e9-8589-b53c70737b76.png">

**Comment by rudysuharyadi** [comment]
Hi, is there any ETA when this will be fixed?

**Comment by rudysuharyadi** [comment]
Is there any update on this?

**Comment by rudysuharyadi** [comment]
Is there any update on this?

**Comment by rudysuharyadi** [comment]
Is version 7 solve this issue?

**Comment by rudysuharyadi** [comment]
Hi @jameshfisher, is there any update with this issue? This issue have been open for more than 3 months now. Is updating to version 7 gonna solve this issue?

**Comment by rudysuharyadi** [comment]
I am sorry if I am bothering you. But, this issue is quite critical in our production apps. Once it freeze, then there is nothing we can do unless kill the app. Our product is a POS, issue like this is really annoyed our user. Imagine when user try to create some bills, and then the freeze issue occured, and then they need to kill the app and repeat the step all over again. Many of our user already churn and didn't want to use our apps anymore because of this. Can you please at least give us some update? @jameshfisher

**Comment by TomKemp** [comment]
Hi @rudysuharyadi. Sorry for the delay in getting back to you about this issue. We haven't investigated this yet therefore the 7.0.0 release is unlikely to address it. I'll try to find some time this week to reproduce it, probably Friday.

**Comment by rudysuharyadi** [comment]
Hi @TomKemp , is there any update with this issue?

**Comment by rudysuharyadi** [comment]
@TomKemp @jameshfisher any update on this issue?

**Comment by TomKemp** [comment]
Hi @rudysuharyadi. I spent a bit of time investigating this.

As far as I can see, it appears to be a problem with your callback rather than the library.  Your callback adds a task to the default queue. That task adds an operation to an `OperationQueue` then blocks the thread waiting for that operation to complete using `waitUntilAllOperationsAreFinished`. I think the operations in the `OperationQueue` are probably being executed on the same thread pool as the default queue so you are getting into a deadlock situation. All the threads are blocked waiting for the `OperationQueue`s to finish, but the tasks in the OperationQueue can't be scheduled because all the threads are blocked.

The same thing happens in this code snippet without the pusher library:
`
        for i in 1...1000 {
            DispatchQueue.global().async {
                print("Dispatch: \(i)")
                let operationQueue = OperationQueue()
                let blockOperation = BlockOperation.init(block: {
                    sleep(5)
                    print("Timer complete: \(i)")
                })
                operationQueue.addOperation(blockOperation)
                operationQueue.waitUntilAllOperationsAreFinished()
                print("Finished: \(i)")
            }
        }
`

![Screenshot 2019-05-15 at 10 44 02](https://user-images.githubusercontent.com/1678620/57765958-6d5b9500-76fe-11e9-8864-26ce87491f6c.png)

This will then also affect the pusher-library, because the `writeQueue` from your screenshot is also an `OperationQueue`, which presumably won't be able to schedule its tasks if all threads in the thread pool are blocked.

That's my current theory for what is going wrong.

If that is what's happening then you would resolve it by modifying your callback code to avoid the deadlock.

**Comment by rudysuharyadi** [comment]
Hi @TomKemp ,

Thanks for your investigation. Your explanation seems right. I will change our code to rely on operation queue depedency instead, even though its a little bit difficult to code, but at least not blocking any thread. 

I just wonder that some of our code in another area also maybe blocking thread, and pusher's writeQueue also maybe use the same thread that can lead to another freeze issue. Isn't it will be wise if pusher also not blocking any thread, especially main thread?

Thanks for your time, explanation, and feedback. I really appreciate it.
