### ISSUE TITLE
App crash on method unbindAll in PusherChannel class

### ISSUE THREAD

**Issue by ankitgarg1mg** [pusher/pusher-websocket-swift#220]
We are using Pusher version 7.0 installed using cocoa pods. While unbinding the event in Pusher, the app is getting crashed in method "func unbindAll(forEventName eventName: String)" in PusherChannel class

<img width="1098" alt="Screen Shot 2019-06-18 at 5 35 54 PM" src="https://user-images.githubusercontent.com/34055785/59680683-94baeb80-91ef-11e9-929c-11bff59b59aa.png">

**Comment by TomKemp** [comment]
Thanks for creating an issue.

How often are you seeing this crash? Are there any particular steps which lead to the crash?

I suspect this may be a similar issue to #219.

**Comment by ankitgarg1mg** [comment]
We are not able to replicate this issue. We are unbinding the event in view controller dealloc and binding event in viewDidLoad. So I guess it won't be a concurrency issue.

**Comment by TomKemp** [comment]
Apologies, I've been delayed in solving this issue.

I'm not certain what is going wrong based on the information I have. All that the `unbindAll` function does is set a key in a dictionary (`eventHandlers` in the stack trace above) so I suspect the exception is due to concurrent access to that dictionary. Internally, the library only ever modifies that dictionary on the main queue, but any calls you make to bind/unbind/unbindAll will modify that dictionary on whichever thread you make the call with, which I suspect is what leads to the exception.

As a work around, you could try wrapping your call to `unbindAll` (probably `bind` too) in a `DispatchQueue.main.async { ... }` so that the call is executed on the main queue. That should ensure the dictionary is only ever modified on the main queue sequentially, avoiding concurrent access.

I'd be grateful if you could let me know if that works. My intended fix for the issue is to ensure the dictionary is only ever accessed internally through a dispatch queue to stop concurrent access. Knowing whether the suggested workaround fixes the issue will help me to confirm that my intended fix will help.

Any other information you can provide about the circumstances in which the error occurs would be helpful.
