### ISSUE TITLE
Library should respect connection closure codes

### ISSUE THREAD

**Issue by TomKemp** [pusher/pusher-websocket-swift#222]
The [Pusher Channels protocol documentation](https://pusher.com/docs/channels/library_auth_reference/pusher-websockets-protocol#connection-closure) specifies that client libraries should not re-establish connections unchanged for error codes 4000-4099, which the library doesn't currently respect.

**Comment by danielrbrowne** [comment]
Having had a look into this - I think the fix for this (and the related closure code logic as specified for codes 4100-4199 where the client should back of for at least 1s) can only be done as part of #277.

This is due to the fact that the closure code is not exposed in the 3.1.1 version of Starscream that is currently used. I.e. it's not present as a parameter on the delegate method `websocketDidDisconnect(socket: WebSocketClient, error: Error?)` whereas it _is_ present in `didReceive(event: WebSocketEvent, client: WebSocket)` with an event of `.disconnected(let reason, let code)`.
