### ISSUE TITLE
Swift 5.0 conversion

### ISSUE THREAD

**Issue by asadali737** [pusher/pusher-websocket-swift#229]
When you are planing to provide Swift 5.0 compatibility?
I am using Xcode 10.3 and Swift 5.0 for my projects. And Xcode continuously warns about Swift 5.0 conversion.

**Comment by leio** [comment]
I tried forcing it to SWIFT_VERSION=5.0 via cocoapods postinstall script in `Podfile`, but the podspec is forcing CryptoSwift and StarScream dependencies from older release cycles, which I read don't have Swift 5 support yet.
Not sure how #218 handled it supposedly

**Comment by jannemecek** [comment]
I don't think #218 really handled it. We use Starscream as a dependency in other libraries and are unable to update to use the latest Pusher because of this (Starscream 3.0.5 vs 3.1.0). I forked the Pusher library and updated the podspec as a temporary measure until this is resolved:
https://github.com/jannemecek/pusher-websocket-swift

**Comment by JonathanDowning** [comment]
This would be resolved by https://github.com/pusher/pusher-websocket-swift/pull/237

**Comment by ruddfawcett** [comment]
Can be closed by #261.

**Comment by TomKemp** [comment]
The library now uses Swift version 5.0 so I am going to close this issue.
