### ISSUE TITLE
Add an option to disable SSL certificate validation

### ISSUE THREAD

**Issue by armandsLa** [pusher/pusher-websocket-swift#236]
### Steps to reproduce

Try connecting to a WSS which uses a self-signed SSL certificate.

### Expected behavior

Be able to connect to hosts which uses self-signed SSL certificates.

### Actual behavior

Connection is not established. ATS configurations doesn't have any effect.

### Any improvements you suggest

Underlying Starscream library has an option to disable SSL validation which solves this issue. Please make this option accessible via the `PusherClientOptions`.

**Comment by LtotheWT** [comment]
hey @armandsLa  did you found a solution for this ?

**Comment by danielrbrowne** [comment]
@armandsLa @LtotheWT What are your specifc use cases for this functionality?

**Comment by danielrbrowne** [comment]
An update:

Pusher Channels offers the ability to optionally connect to non-TLS connections (see the discussion on the `useTLS` option on the `PusherClientOptions` object in the README). However since disabling SSL certification validation on the client side defeats the purpose of using TLS, we have no plans to introduce this feature.
