### ISSUE TITLE
[iOS] on pusher swift 10.0.0,   changedConnectionState seems not to be triggering properly

### ISSUE THREAD

**Issue by dganzella** [pusher/pusher-websocket-swift#369]
### Steps to reproduce

Turn off-and-on wifi on an iOS device while in a pusher session, disconnect and recconect multiple times on a presence channel.

### Expected behavior

All messages from

```
  public func changedConnectionState(from old: ConnectionState, to new: ConnectionState) {
    print("old connection state: \(old.stringValue()) -> new state: \(new.stringValue())")
```

Should appear (disconnecting, reconnecting, reconnected, etc.)

### Actual behavior

Sometimes this method is not triggered. Sometimes for disconnection, sometimes for reconnection. Which causes the UI from my flutter app not to propper respond.

**Comment by dganzella** [comment]
Seems to be happening also on 9.2.2

[PUSHER DEBUG] Network connection became unviable
[tcp] nw_proto_tcp_route_init [C3.1:3] no mtu received

is the only message I receive. not printing 
print("old connection state: \(old.stringValue()) -> new state: \(new.stringValue())")

at all

**Comment by dganzella** [comment]
Seems to also happens on 9.0.0, its only not happening on 8.0

Like the other guy said on the other thread, 8.0 is not as bad

**Comment by miquelbeltran** [comment]
My guess is because the Reachability dependency was removed: https://github.com/pusher/pusher-websocket-swift/commit/02aeab65c0ac9fb81ad131370159a9af0c90e946 and this also removed this section of code: 

https://github.com/pusher/pusher-websocket-swift/commit/02aeab65c0ac9fb81ad131370159a9af0c90e946#diff-53e65cfa055a12c2f09666ac710e9eafc9643f5fb418cbfb5e0bae4bbac10410L321-L324

which was in charge of reconnecting

**Comment by benw-pusher** [comment]
@dganzella you mention is doesn't happen on v8, and that it is not as bad on v8. Could you just clarify this? I'm confused as to whether the issue is not present in version 8, or if it _is_ present just not encountered as frequently.

**Comment by mirrorlink** [comment]
> @dganzella you mention is doesn't happen on v8, and that it is not as bad on v8. Could you just clarify this? I'm confused as to whether the issue is not present in version 8, or if it _is_ present just not encountered as frequently.

Hey ben! (I'm dganzella) I'm happy that pusher is looking into it.

What I meant is, on v8, I can get the disconnetion events, but on v8, the users get duplicated. The members array of a channel is never cleared properly. And that happens when disconnecting and reconnecting, you can see more about it here:

https://github.com/pusher/pusher-websocket-swift/issues/370

Besides, there is something else about v8 that I'd like to tell. It's implementation differs from the android implementation on the reconnecting process.

```
    pusherConnectState = SessionManager()
        .pusherWrapper
        .pusher!
        .onConnectivityChanged
        .listen((state) async {
      if (state == PusherConnectionState.reconnecting) {
        iOSReconnectAttempts++;
       (...)
      } else if (state == PusherConnectionState.connected ) {
        iOSReconnectAttempts = 0;
        (...)
      } else if (state == PusherConnectionState.disconnected) {
        if (Platform.isAndroid) {
          doDisconnect(afterSessionPages.Waiting, {});
        } else {
          if (iOSReconnectAttempts >= 6) {
            doDisconnect(afterSessionPages.Waiting, {});
          }
        }
      }
    }, onDone: () {}, onError: (error) {});
```

on Android, you only get the event like it should be. You receive a 'disconnected' event once after exhausting reconnection attempts, and its final.

but on iOS, version 8.0, you actually receive the reconnecting AND disconnected multiple times. And I had to count the reconnecting attempts myself to then decide that the 'disconnected' I received is the actual final one.
