### ISSUE TITLE
missing required module CTweetNacl when using SPM

### ISSUE THREAD

**Issue by brianguertin** [pusher/pusher-websocket-swift#396]
I'm using SPM to include this module in my Package.swift, which I'm then trying to build into an iOS app.

However the build fails due to missing `CTweetNacl` module.

I suspect it needs to be exported in your Package.swift in order to be picked up.

Similar issue to https://github.com/pusher/pusher-websocket-swift/issues/371 which was auto-closed (despite not being fixed)

**Comment by benjamin-tang-pusher** [comment]
Did you add the package to your project using with File (or right click)->Add Packages... . If so, did you then set the dependency rule to 10.1.1. (or pin to the master branch)? As currently its defaulting to an older version.

**Comment by benjamin-tang-pusher** [comment]
Sorry, I just reread this, and since you've got your own Package.swift, you must be giving it to someone else to import (or importing it again into your own app)

If thats the case, then I can give you a workaround repo, which has manually copied both dependencies' source files into the project, which you can run yourself. Its not an ideal workaround, but tweetnacl-swiftwrap uses C files, which neither SPM (nor Carthage) play well with, despite spending alot of time tinkering with spm and its xcodeproj file. I helped [TiagoLira](https://github.com/TiagoLira) in #371 with this, but I will remake a more minimalist project for you. I will let you know when I've uploaded it.

**Comment by brianguertin** [comment]
Yeah, I'm actually have a library (so I have Package.swift), thanks for your help, it is appreciated :)

**Comment by benjamin-tang-pusher** [comment]
I've uploaded it to this repo: https://github.com/benjamin-tang-pusher/pusher-socket-swift-depsincluded. The project builds, and the tests pass. You cannot use SPM to import it, however, because the sources folder now has mixed language (C files), so I just need to test if it can be used by adding the project.

**Comment by benjamin-tang-pusher** [comment]
You can use the above repo for your project:

1. Clone it (probably into your project's directory)
2. In your XCode project, click your project file, then target, and in framework and library, click the + icon
3. Click add other
4. Click the project file of my lib
5. Click the + icon again, and select PusherSwift.xcframework

Now you can import PusherSwift into your project and use it.

**Comment by brianguertin** [comment]
Thanks so much!

You're instructions say project file, but this is a Swift package. So, will the resulting PusherSwift.xcframework work as a binary dependency in a swift package.

I'll give it a try when I have a moment

**Comment by brianguertin** [comment]
Thanks for your insight, I think this is really just for us to deal with on our end :)
