### ISSUE TITLE
Connect to private server without APP_KEY

### ISSUE THREAD

**Issue by Darkwonder** [pusher/pusher-websocket-swift#93]
I am doing a chat demo app for a client. The web dev team has setup a private server without the pusher library. They used something else. 

I am trying to connect but I can't. My code works when I try to connect with a APP_KEY on the regular account from www.pusher.com

My question is:
A) Is it possible to connect to a private server instead of pusher?
B) Is it possible to connect at all without the APP_KEY?

Any advice is welcome.

**Comment by hamchapman** [comment]
If you implemented the [Pusher protocol](https://pusher.com/docs/pusher_protocol) on your private server then you could use this library to connect to it. Or you could implement some version of it that doesn't require app keys in order to connect (you'd essentially be making it a non-multi-tenant system). 

That's not really what this library was designed for though. You're better off using the [underlying websocket library](https://github.com/daltoniam/Starscream) if you want to use websockets in Swift without any of the Pusher setup.

**Comment by MladenBekavac** [comment]
I had a feeling that the pusher library was intended to be used via the Web API with the key and no other way. The private server is just a middle man and still needs those protocols. Thank you.

**Comment by hamchapman** [comment]
You can use Pusher on pretty much any platform. We have libraries for users to use natively on iOS and Android, in web browsers on any device where you can run Javascript, and the vast majority of languages that are traditionally thought of as server-side, e.g. Ruby, Node, Python, PHP etc

Is the private server just a proxy? I think I need more info on your set up for me to be able to help more! Thanks

**Comment by MladenBekavac** [comment]
Thank you for the quick response. The web dev team leader and me are not allowed to share project details. However, maybe you could help me with this informations:

Q1. The APP_KEY has always the same lenght of characters, right?
Mine has 128. It has been given to me by the web dev leader. 
Q2. They should have gotten it from the www.pusher.com website?
Q3. The APP_KEY from : https://dashboard.pusher.com/apps/MY_USER_ID/keys
has 20. Since mine has 128 characters, this can't be the correct APP_KEY?
Q4. Without the APP_KEY I cannot connect with my iOS app to the pusher service (my current version)? I am currently using:

> pod 'PusherSwift', git: 'https://github.com/pusher/pusher-websocket-swift.git', branch: 'swift-2.3'

**Comment by hamchapman** [comment]
1) Correct
2) Correct
3) Correct, it won't be a valid Pusher app key
4) Correct

**Comment by jasmeen-ucreate** [comment]
Hii, Anybody help please me regarding Pusher. I have Xcode version 7.3 along with swift version 2.3. So I want to know the compatible version of pusher with swift 2.3 and xcode 7.3
